[package]
name = "vyayah"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.4.18"
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive", "serde_derive"] }
serde_json = "1.0.111"
